name: toonx
description: ToonX - Cartoonify images using DeepAI CartoonGAN
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & image handling
  http: ^0.13.6
  image_picker: ^0.8.7+4

  # Storage & permissions
  path_provider: ^2.0.14
  permission_handler: ^10.4.0
  gallery_saver: ^2.3.2

  # UI / animations
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

 # assets:
 #   - assets/images/
